# Generated by Django 3.2 on 2021-11-14 07:27

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='img2',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img3',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img4',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img5',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='img6',
            field=models.ImageField(blank=True, null=True, upload_to='post_img'),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='discription',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 13, 27, 31, 366675)),
        ),
    ]
