# Generated by Django 3.2 on 2021-11-14 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_auto_20211114_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='get_in_touch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 15, 41, 48, 326944)),
        ),
    ]
