# Generated by Django 3.2 on 2021-11-14 09:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0004_auto_20211114_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='get_in_touch',
            old_name='email',
            new_name='user_email',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 15, 47, 55, 109671)),
        ),
        migrations.AlterField(
            model_name='get_in_touch',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 15, 47, 55, 110673)),
        ),
    ]
