# Generated by Django 3.2 on 2021-11-14 12:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogapp', '0005_auto_20211114_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 18, 32, 11, 998508)),
        ),
        migrations.AlterField(
            model_name='get_in_touch',
            name='time',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 18, 32, 11, 999503)),
        ),
        migrations.CreateModel(
            name='Blogs_Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('time', models.DateTimeField(blank=True, default=datetime.datetime(2021, 11, 14, 18, 32, 11, 999503))),
                ('Blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogapp.blog_post')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
